"""Domain enums. Stored as strings (portable across PostgreSQL/SQLite)."""

from enum import StrEnum


class UserRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    VIEWER = "VIEWER"


class MetaLoginMode(StrEnum):
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"


class InstagramAccountType(StrEnum):
    BUSINESS = "BUSINESS"
    CREATOR = "CREATOR"
    UNKNOWN = "UNKNOWN"


class ContentType(StrEnum):
    POST = "POST"
    CAROUSEL = "CAROUSEL"
    REELS = "REELS"
    STORY = "STORY"


class ContentStatus(StrEnum):
    DRAFT = "DRAFT"
    GENERATING = "GENERATING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    EDIT_REQUESTED = "EDIT_REQUESTED"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class ContentLanguage(StrEnum):
    UZ = "uz"
    RU = "ru"
    EN = "en"


class AssetKind(StrEnum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"


class ScheduleStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    DONE = "DONE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EDIT_REQUESTED = "EDIT_REQUESTED"


class ApprovalChannel(StrEnum):
    WEB = "WEB"
    TELEGRAM = "TELEGRAM"


class ActorType(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class AIJobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class AuditAction(StrEnum):
    CONTENT_CREATED = "CONTENT_CREATED"
    CONTENT_UPDATED = "CONTENT_UPDATED"
    CONTENT_VERSION_CREATED = "CONTENT_VERSION_CREATED"
    CONTENT_SUBMITTED_FOR_REVIEW = "CONTENT_SUBMITTED_FOR_REVIEW"
    CONTENT_EDIT_REQUESTED = "CONTENT_EDIT_REQUESTED"
    CONTENT_APPROVED = "CONTENT_APPROVED"
    CONTENT_APPROVAL_INVALIDATED = "CONTENT_APPROVAL_INVALIDATED"
    CONTENT_REJECTED = "CONTENT_REJECTED"
    CONTENT_SCHEDULED = "CONTENT_SCHEDULED"
    CONTENT_SCHEDULE_CANCELLED = "CONTENT_SCHEDULE_CANCELLED"
    CONTENT_GENERATION_STARTED = "CONTENT_GENERATION_STARTED"
    CONTENT_GENERATION_FAILED = "CONTENT_GENERATION_FAILED"
    CONTENT_PUBLISH_STARTED = "CONTENT_PUBLISH_STARTED"
    CONTENT_PUBLISH_SUCCEEDED = "CONTENT_PUBLISH_SUCCEEDED"
    CONTENT_PUBLISH_FAILED = "CONTENT_PUBLISH_FAILED"
    CONTENT_DELETED = "CONTENT_DELETED"
    ASSET_ADDED = "ASSET_ADDED"
    ASSET_REMOVED = "ASSET_REMOVED"
    APPROVAL_DENIED = "APPROVAL_DENIED"
    STATE_TRANSITION_DENIED = "STATE_TRANSITION_DENIED"
    BRAND_PROFILE_CREATED = "BRAND_PROFILE_CREATED"
    BRAND_PROFILE_UPDATED = "BRAND_PROFILE_UPDATED"
    INSTAGRAM_ACCOUNT_LINKED = "INSTAGRAM_ACCOUNT_LINKED"
    INSTAGRAM_ACCOUNT_DISCONNECTED = "INSTAGRAM_ACCOUNT_DISCONNECTED"
    OAUTH_TOKEN_STORED = "OAUTH_TOKEN_STORED"  # noqa: S105
    OAUTH_TOKEN_REVOKED = "OAUTH_TOKEN_REVOKED"  # noqa: S105
    AI_JOB_STARTED = "AI_JOB_STARTED"
    AI_JOB_SUCCEEDED = "AI_JOB_SUCCEEDED"
    AI_JOB_FAILED = "AI_JOB_FAILED"
    SEED_APPLIED = "SEED_APPLIED"
