"""instagram oauth states and data deletion

Revision ID: c600c9d62a46
Revises: b8c9e1e91e47
Create Date: 2026-10-09 04:07:56.795099
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "c600c9d62a46"
down_revision: str | None = "b8c9e1e91e47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_deletion_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("confirmation_code", sa.String(length=64), nullable=False),
        sa.Column("platform_user_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_deletion_requests")),
        sa.UniqueConstraint(
            "confirmation_code", name=op.f("uq_data_deletion_requests_confirmation_code")
        ),
    )
    op.create_index(
        op.f("ix_data_deletion_requests_platform_user_id"),
        "data_deletion_requests",
        ["platform_user_id"],
        unique=False,
    )
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_states")),
        sa.UniqueConstraint("state_hash", name=op.f("uq_oauth_states_state_hash")),
    )
    op.create_index(op.f("ix_oauth_states_user_id"), "oauth_states", ["user_id"], unique=False)
    with op.batch_alter_table("instagram_accounts") as batch:
        batch.add_column(sa.Column("ig_app_scoped_id", sa.String(length=64), nullable=True))
        batch.add_column(sa.Column("profile_picture_url", sa.String(length=1000), nullable=True))
        batch.create_index(op.f("ix_instagram_accounts_ig_app_scoped_id"), ["ig_app_scoped_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instagram_accounts") as batch:
        batch.drop_index(op.f("ix_instagram_accounts_ig_app_scoped_id"))
        batch.drop_column("profile_picture_url")
        batch.drop_column("ig_app_scoped_id")
    op.drop_index(op.f("ix_oauth_states_user_id"), table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index(
        op.f("ix_data_deletion_requests_platform_user_id"), table_name="data_deletion_requests"
    )
    op.drop_table("data_deletion_requests")
    # ### end Alembic commands ###
