"""initial schema

Revision ID: 22d94eda60d4
Revises:
Create Date: 2026-10-08 17:59:56.494660
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "22d94eda60d4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("niche", sa.String(length=120), nullable=True),
        sa.Column("voice", sa.JSON(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("forbidden_rules", sa.JSON(), nullable=False),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("visual_style", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_brand_profiles_name")),
    )
    op.create_index(
        op.f("ix_brand_profiles_deleted_at"), "brand_profiles", ["deleted_at"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "VIEWER", name="userrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "instagram_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ig_user_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column(
            "account_type",
            sa.Enum(
                "BUSINESS",
                "CREATOR",
                "UNKNOWN",
                name="instagramaccounttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "login_mode",
            sa.Enum("instagram", "facebook", name="metaloginmode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("facebook_page_id", sa.String(length=64), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_instagram_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instagram_accounts")),
        sa.UniqueConstraint("ig_user_id", name=op.f("uq_instagram_accounts_ig_user_id")),
    )
    op.create_index(
        op.f("ix_instagram_accounts_deleted_at"), "instagram_accounts", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_instagram_accounts_user_id"), "instagram_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instagram_account_id", sa.Integer(), nullable=True),
        sa.Column("brand_profile_id", sa.Integer(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum(
                "POST",
                "CAROUSEL",
                "REELS",
                "STORY",
                name="contenttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "GENERATING",
                "READY_FOR_REVIEW",
                "EDIT_REQUESTED",
                "APPROVED",
                "SCHEDULED",
                "PUBLISHING",
                "PUBLISHED",
                "FAILED",
                "REJECTED",
                name="contentstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("uz", "ru", "en", name="contentlanguage", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column("topic", sa.String(length=300), nullable=True),
        sa.Column("hook", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("hashtags", sa.JSON(), nullable=False),
        sa.Column("cta", sa.Text(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("visual_prompt", sa.Text(), nullable=True),
        sa.Column("aspect_ratio", sa.String(length=10), nullable=True),
        sa.Column(
            "created_by",
            sa.Enum("HUMAN", "AGENT", "SYSTEM", name="actortype", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("ig_media_id", sa.String(length=64), nullable=True),
        sa.Column("ig_permalink", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_profile_id"],
            ["brand_profiles.id"],
            name=op.f("fk_contents_brand_profile_id_brand_profiles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_contents_instagram_account_id_instagram_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contents")),
        sa.UniqueConstraint("ig_media_id", name=op.f("uq_contents_ig_media_id")),
    )
    op.create_index(
        op.f("ix_contents_brand_profile_id"), "contents", ["brand_profile_id"], unique=False
    )
    op.create_index(op.f("ix_contents_deleted_at"), "contents", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_contents_instagram_account_id"), "contents", ["instagram_account_id"], unique=False
    )
    op.create_index(
        "ix_contents_status_created", "contents", ["status", "created_at"], unique=False
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instagram_account_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("token_ciphertext", sa.Text(), nullable=False),
        sa.Column("token_type", sa.String(length=30), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_oauth_tokens_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_tokens")),
    )
    op.create_index(
        op.f("ix_oauth_tokens_expires_at"), "oauth_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_tokens_instagram_account_id"),
        "oauth_tokens",
        ["instagram_account_id"],
        unique=False,
    )
    op.create_table(
        "ai_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=50), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="aijobstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_ai_jobs_content_id_contents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_jobs")),
    )
    op.create_index(op.f("ix_ai_jobs_content_id"), "ai_jobs", ["content_id"], unique=False)
    op.create_index("ix_ai_jobs_status_created", "ai_jobs", ["status", "created_at"], unique=False)
    op.create_table(
        "analytics_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instagram_account_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("api_version", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_analytics_snapshots_content_id_contents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_analytics_snapshots_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_snapshots")),
    )
    op.create_index(
        op.f("ix_analytics_snapshots_content_id"),
        "analytics_snapshots",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_snapshots_instagram_account_id"),
        "analytics_snapshots",
        ["instagram_account_id"],
        unique=False,
    )
    op.create_index(
        "ix_analytics_snapshots_scope_captured",
        "analytics_snapshots",
        ["scope", "captured_at"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVED",
                "REJECTED",
                "EDIT_REQUESTED",
                name="approvaldecision",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("decided_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("WEB", "TELEGRAM", name="approvalchannel", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_approvals_content_id_contents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_approvals_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "content_id",
            "content_version",
            "decision",
            name=op.f("uq_approvals_content_id_content_version_decision"),
        ),
    )
    op.create_index(op.f("ix_approvals_content_id"), "approvals", ["content_id"], unique=False)
    op.create_index(
        op.f("ix_approvals_decided_by_user_id"), "approvals", ["decided_by_user_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum("HUMAN", "AGENT", "SYSTEM", name="actortype", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_name", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_audit_logs_content_id_contents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_action_ts", "audit_logs", ["action", "timestamp"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_content_id"), "audit_logs", ["content_id"], unique=False)
    op.create_table(
        "content_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("IMAGE", "VIDEO", name="assetkind", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("public_url", sa.String(length=1000), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("generation_prompt", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_content_assets_content_id_contents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_assets")),
    )
    op.create_index(
        op.f("ix_content_assets_content_id"), "content_assets", ["content_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_assets_deleted_at"), "content_assets", ["deleted_at"], unique=False
    )
    op.create_table(
        "content_performance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("engagement_rate", sa.Float(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_content_performance_content_id_contents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_performance")),
        sa.UniqueConstraint("content_id", name=op.f("uq_content_performance_content_id")),
    )
    op.create_table(
        "content_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "DONE",
                "FAILED",
                "CANCELLED",
                name="schedulestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("ig_container_id", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_content_schedules_content_id_contents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_schedules")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_content_schedules_idempotency_key")),
    )
    op.create_index(
        op.f("ix_content_schedules_content_id"), "content_schedules", ["content_id"], unique=False
    )
    op.create_index(
        "ix_content_schedules_status_at",
        "content_schedules",
        ["status", "scheduled_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_schedules_status_at", table_name="content_schedules")
    op.drop_index(op.f("ix_content_schedules_content_id"), table_name="content_schedules")
    op.drop_table("content_schedules")
    op.drop_table("content_performance")
    op.drop_index(op.f("ix_content_assets_deleted_at"), table_name="content_assets")
    op.drop_index(op.f("ix_content_assets_content_id"), table_name="content_assets")
    op.drop_table("content_assets")
    op.drop_index(op.f("ix_audit_logs_content_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_ts", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_approvals_decided_by_user_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_content_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_analytics_snapshots_scope_captured", table_name="analytics_snapshots")
    op.drop_index(
        op.f("ix_analytics_snapshots_instagram_account_id"), table_name="analytics_snapshots"
    )
    op.drop_index(op.f("ix_analytics_snapshots_content_id"), table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    op.drop_index("ix_ai_jobs_status_created", table_name="ai_jobs")
    op.drop_index(op.f("ix_ai_jobs_content_id"), table_name="ai_jobs")
    op.drop_table("ai_jobs")
    op.drop_index(op.f("ix_oauth_tokens_instagram_account_id"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_expires_at"), table_name="oauth_tokens")
    op.drop_table("oauth_tokens")
    op.drop_index("ix_contents_status_created", table_name="contents")
    op.drop_index(op.f("ix_contents_instagram_account_id"), table_name="contents")
    op.drop_index(op.f("ix_contents_deleted_at"), table_name="contents")
    op.drop_index(op.f("ix_contents_brand_profile_id"), table_name="contents")
    op.drop_table("contents")
    op.drop_index(op.f("ix_instagram_accounts_user_id"), table_name="instagram_accounts")
    op.drop_index(op.f("ix_instagram_accounts_deleted_at"), table_name="instagram_accounts")
    op.drop_table("instagram_accounts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_brand_profiles_deleted_at"), table_name="brand_profiles")
    op.drop_table("brand_profiles")
    # ### end Alembic commands ###
