"""initial schema

Revision ID: f24f19f928c7
Revises:
Create Date: 2026-10-01 14:36:00.879239
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f24f19f928c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('active_workspace_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_workspace_id'], ['workspaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('telegram_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_telegram_accounts_telegram_user_id'), 'telegram_accounts', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_user_id'), 'telegram_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_workspace_id'), 'telegram_accounts', ['workspace_id'], unique=False)
    op.create_table('telegram_link_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_link_challenges_code_hash'), 'telegram_link_challenges', ['code_hash'], unique=True)
    op.create_index(op.f('ix_telegram_link_challenges_user_id'), 'telegram_link_challenges', ['user_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('task', sa.String(length=16000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_created_by_user_id'), 'workflows', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    op.create_table('workspace_billing',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('trial_started_at', sa.Integer(), nullable=False),
    sa.Column('trial_ends_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('simulated_payment_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('workspace_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'metric', 'period_start')
    )
    op.create_index(op.f('ix_workspace_usage_workspace_id'), 'workspace_usage', ['workspace_id'], unique=False)
    op.create_table('workflow_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('output', sa.String(length=16000), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'sequence')
    )
    op.create_index(op.f('ix_workflow_phases_workflow_id'), 'workflow_phases', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_phases_workflow_id'), table_name='workflow_phases')
    op.drop_table('workflow_phases')
    op.drop_index(op.f('ix_workspace_usage_workspace_id'), table_name='workspace_usage')
    op.drop_table('workspace_usage')
    op.drop_table('workspace_billing')
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_by_user_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_telegram_link_challenges_user_id'), table_name='telegram_link_challenges')
    op.drop_index(op.f('ix_telegram_link_challenges_code_hash'), table_name='telegram_link_challenges')
    op.drop_table('telegram_link_challenges')
    op.drop_index(op.f('ix_telegram_accounts_workspace_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_user_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_telegram_user_id'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
